WITH STRATA AS (
SELECT AREA_ID AS STRATUM, DESCRIPTION FROM GAP_PRODUCTS.AKFIN_AREA
WHERE AREA_TYPE = 'STRATUM'
AND SURVEY_DEFINITION_ID
-- insert survey
),

REG_AREAS AS (
SELECT AREA_ID, DESCRIPTION AS SUBAREA_NAME, DESIGN_YEAR FROM GAP_PRODUCTS.AKFIN_AREA
WHERE AREA_TYPE = 'REGULATORY AREA'
AND SURVEY_DEFINITION_ID
-- insert survey
)

SELECT * FROM REG_AREAS
JOIN (SELECT STRATUM, AREA_ID FROM GAP_PRODUCTS.AKFIN_STRATUM_GROUPS) USING (AREA_ID)
JOIN STRATA USING (STRATUM)
ORDER BY AREA_ID, STRATUM;
